name: Monitor de Notas USAC

on:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 minutos
  workflow_dispatch:           # ejecución manual desde GitHub

jobs:
  check:
    runs-on: ubuntu-latest
    environment: NotiSecrets   # <-- aquí se accede a los secretos del environment

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install requests pdfplumber

      - name: Restaurar estado anterior
        uses: actions/cache@v4
        with:
          path: state.json
          key: state-${{ github.run_id }}
          restore-keys: |
            state-

      - name: Ejecutar monitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python check_notas.py

      - name: Guardar estado actualizado
        uses: actions/cache/save@v4
        if: always()
        with:
          path: state.json
          key: state-${{ github.run_id }}
